### PR TITLE
Pass a safeuri to BadURIError again

### LINKED ISSUE #630: Retry and DLQ issues
After building my own plugin (v7.3.8) with custom RETRYABLE_CODES and DLQ_CODES configured I ran into multiple issues during testing.

In `lib/logstash/outputs/elasticsearch/common.rb`: 
```ruby
if RETRYABLE_CODES.include?(e.response_code)
    log_hash = {:code => e.response_code, :url => e.url.sanitized.to_s}
```
I get failures (at least) with a 502 response as the `sanitized` method does not exist on the response url object. This will lead to a catchall retry mechanism kicking in but throws exceptions.

Other issue I found is with a 404 response code and DLQ. In: `lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb` a 404 is excluded from throwing an exception due to possible template installation failure. Problem is that because `BadResponseCodeError` is not thrown, the Retry and DLQ logic is abandoned due to an exception being thrown in the `join_bulk_responses()`, which fails on parsing the response body.

Here a snippet of that exception:
```
[2017-08-01T21:42:01,126][ERROR][logstash.outputs.elasticsearch] An unknown error occurred sending a bulk request to Elasticsearch. We will retry indefinitely {:error_message=>"undefined method `[]' for nil:NilClass", :error_class=>"NoMethodError", :backtrace=>["/usr/share/logstash/vendor/local_gems/c95b210f/logstash-output-elasticsearch-7.3.8-java/lib/logstash/outputs/elasticsearch/http_client.rb:131:in `join_bulk_responses'", "org/jruby/RubyEnumerable.java:1456:in `any?'", "/usr/share/logstash/vendor/local_gems/c95b210f/logstash-output-elasticsearch-7.3.8-java/lib/logstash/outputs/elasticsearch/http_client.rb:130:in `join_bulk_responses'", "/usr/share/logstash/vendor/local_gems/c95b210f/logstash-output-elasticsearch-7.3.8-java/lib/logstash/outputs/elasticsearch/http_client.rb:126:in `bulk'"
```

### PR DESCRIPTION
**Pull request by andrewvc**
Partially fixes #630 by reverting behavior where a URI was passed to `BadResponseCodeError` errors.

This bug was introduced in https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/9711709d3b6a258f43b9c9005cc9485bf297d8e7

### CODE REVIEW

File: spec/unit/outputs/elasticsearch/http_client/manticore_adapter_spec.rb [hunk 1]
```diff
@@ -44,19 +44,35 @@
     end
   end
 
+  describe "bad response codes" do
+    let(:uri) { ::LogStash::Util::SafeURI.new("http://localhost:9200") }
+
+    it "should raise a bad response code error" do
```
Comment (jsvd) [inline spec/unit/outputs/elasticsearch/http_client/manticore_adapter_spec.rb]: I may be reading this wrong, but I don't see a point to this test, since we mock the response, stub it, and then check we got the values from the mock.
Also, this test does not break in master.

Comment (andrewvc) [inline spec/unit/outputs/elasticsearch/http_client/manticore_adapter_spec.rb]: Yes, I have no idea what I was thinking here

Comment (andrewvc) [inline spec/unit/outputs/elasticsearch/http_client/manticore_adapter_spec.rb]: OK, I just pushed, the test should actually make sense now.

**Comment by jsvd** [comment]
@andrewvc can you backport this to 7.x? currently logstash 5.6.0 (v7.4.0 of this plugin) can trigger this in multiple situations (x-pack only on logstash side, wrong bulk_path, etc):

```
/tmp/logstash-5.6.0 % echo "hello" | bin/logstash -e "output { elasticsearch { bulk_path => '/wrwr' } }"
Sending Logstash's logs to /tmp/logstash-5.6.0/logs which is now configured via log4j2.properties
[2017-09-18T11:45:24,692][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://127.0.0.1:9200/]}}
[2017-09-18T11:45:24,694][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://127.0.0.1:9200/, :path=>"/"}
[2017-09-18T11:45:24,829][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"http://127.0.0.1:9200/"}
[2017-09-18T11:45:24,830][INFO ][logstash.outputs.elasticsearch] Using mapping template from {:path=>nil}
[2017-09-18T11:45:24,872][INFO ][logstash.outputs.elasticsearch] Attempting to install template {:manage_template=>{"template"=>"logstash-*", "version"=>50001, "settings"=>{"index.refresh_interval"=>"5s"}, "mappings"=>{"_default_"=>{"_all"=>{"enabled"=>true, "norms"=>false}, "dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date", "include_in_all"=>false}, "@version"=>{"type"=>"keyword", "include_in_all"=>false}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}}
[2017-09-18T11:45:24,882][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//127.0.0.1"]}
[2017-09-18T11:45:24,889][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>500}
[2017-09-18T11:45:24,899][INFO ][logstash.pipeline        ] Pipeline main started
[2017-09-18T11:45:24,980][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-09-18T11:45:24,982][ERROR][logstash.outputs.elasticsearch] Encountered an unexpected error submitting a bulk request! Will retry. {:error_message=>"undefined method `sanitized' for \"http://127.0.0.1:9200/wrwr\":String", :class=>"NoMethodError", :backtrace=>["/tmp/logstash-5.6.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.0-java/lib/logstash/outputs/elasticsearch/common.rb:249:in `safe_bulk'", "/tmp/logstash-5.6.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.0-java/lib/logstash/outputs/elasticsearch/common.rb:119:in `submit'", "/tmp/logstash-5.6.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.0-java/lib/logstash/outputs/elasticsearch/common.rb:87:in `retrying_submit'", "/tmp/logstash-5.6.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.0-java/lib/logstash/outputs/elasticsearch/common.rb:38:in `multi_receive'", "/tmp/logstash-5.6.0/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:13:in `multi_receive'", "/tmp/logstash-5.6.0/logstash-core/lib/logstash/output_delegator.rb:49:in `multi_receive'", "/tmp/logstash-5.6.0/logstash-core/lib/logstash/pipeline.rb:436:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/tmp/logstash-5.6.0/logstash-core/lib/logstash/pipeline.rb:435:in `output_batch'", "/tmp/logstash-5.6.0/logstash-core/lib/logstash/pipeline.rb:381:in `worker_loop'", "/tmp/logstash-5.6.0/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}
[2017-09-18T11:45:26,995][ERROR][logstash.outputs.elasticsearch] Encountered an unexpected error submitting a bulk request! Will retry. {:error_message=>"undefined method `sanitized' for \"http://127.0.0.1:9200/wrwr\":String", :class=>"NoMethodError", :backtrace=>["/tmp/logstash-5.6.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.0-java/lib/logstash/outputs/elasticsearch/common.rb:249:in `safe_bulk'", "/tmp/logstash-5.6.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.0-java/lib/logstash/outputs/elasticsearch/common.rb:119:in `submit'", "/tmp/logstash-5.6.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.0-java/lib/logstash/outputs/elasticsearch/common.rb:87:in `retrying_submit'", "/tmp/logstash-5.6.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.0-java/lib/logstash/outputs/elasticsearch/common.rb:38:in `multi_receive'", "/tmp/logstash-5.6.0/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:13:in `multi_receive'", "/tmp/logstash-5.6.0/logstash-core/lib/logstash/output_delegator.rb:49:in `multi_receive'", "/tmp/logstash-5.6.0/logstash-core/lib/logstash/pipeline.rb:436:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/tmp/logstash-5.6.0/logstash-core/lib/logstash/pipeline.rb:435:in `output_batch'", "/tmp/logstash-5.6.0/logstash-core/lib/logstash/pipeline.rb:381:in `worker_loop'", "/tmp/logstash-5.6.0/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}
```

**Comment by jsvd** [comment]
this is also now fixes in 7.4.2
